/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalisisRouteImport } from './routes/analisis'
import { Route as EdukasiRouteImport } from './routes/edukasi'
import { Route as KalenderEkonomiRouteImport } from './routes/kalender-ekonomi'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as AnalisisSlugRouteImport } from './routes/analisis.$slug'
import { Route as EdukasiSlugRouteImport } from './routes/edukasi.$slug'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisisRoute = AnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => rootRouteImport,
} as any)
const EdukasiRoute = EdukasiRouteImport.update({
  id: '/edukasi',
  path: '/edukasi',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderEkonomiRoute = KalenderEkonomiRouteImport.update({
  id: '/kalender-ekonomi',
  path: '/kalender-ekonomi',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisisSlugRoute = AnalisisSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AnalisisRoute,
} as any)
const EdukasiSlugRoute = EdukasiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EdukasiRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRouteWithChildren
  '/edukasi': typeof EdukasiRouteWithChildren
  '/kalender-ekonomi': typeof KalenderEkonomiRoute
  '/kontak': typeof KontakRoute
  '/news': typeof NewsRouteWithChildren
  '/profil': typeof ProfilRoute
  '/studio': typeof StudioRoute
  '/analisis/$slug': typeof AnalisisSlugRoute
  '/edukasi/$slug': typeof EdukasiSlugRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRouteWithChildren
  '/edukasi': typeof EdukasiRouteWithChildren
  '/kalender-ekonomi': typeof KalenderEkonomiRoute
  '/kontak': typeof KontakRoute
  '/news': typeof NewsRouteWithChildren
  '/profil': typeof ProfilRoute
  '/studio': typeof StudioRoute
  '/analisis/$slug': typeof AnalisisSlugRoute
  '/edukasi/$slug': typeof EdukasiSlugRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRouteWithChildren
  '/edukasi': typeof EdukasiRouteWithChildren
  '/kalender-ekonomi': typeof KalenderEkonomiRoute
  '/kontak': typeof KontakRoute
  '/news': typeof NewsRouteWithChildren
  '/profil': typeof ProfilRoute
  '/studio': typeof StudioRoute
  '/analisis/$slug': typeof AnalisisSlugRoute
  '/edukasi/$slug': typeof EdukasiSlugRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analisis'
    | '/edukasi'
    | '/kalender-ekonomi'
    | '/kontak'
    | '/news'
    | '/profil'
    | '/studio'
    | '/analisis/$slug'
    | '/edukasi/$slug'
    | '/news/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analisis'
    | '/edukasi'
    | '/kalender-ekonomi'
    | '/kontak'
    | '/news'
    | '/profil'
    | '/studio'
    | '/analisis/$slug'
    | '/edukasi/$slug'
    | '/news/$slug'
  id:
    | '__root__'
    | '/'
    | '/analisis'
    | '/edukasi'
    | '/kalender-ekonomi'
    | '/kontak'
    | '/news'
    | '/profil'
    | '/studio'
    | '/analisis/$slug'
    | '/edukasi/$slug'
    | '/news/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisisRoute: typeof AnalisisRouteWithChildren
  EdukasiRoute: typeof EdukasiRouteWithChildren
  KalenderEkonomiRoute: typeof KalenderEkonomiRoute
  KontakRoute: typeof KontakRoute
  NewsRoute: typeof NewsRouteWithChildren
  ProfilRoute: typeof ProfilRoute
  StudioRoute: typeof StudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisis': {
      id: '/analisis'
      path: '/analisis'
      fullPath: '/analisis'
      preLoaderRoute: typeof AnalisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edukasi': {
      id: '/edukasi'
      path: '/edukasi'
      fullPath: '/edukasi'
      preLoaderRoute: typeof EdukasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender-ekonomi': {
      id: '/kalender-ekonomi'
      path: '/kalender-ekonomi'
      fullPath: '/kalender-ekonomi'
      preLoaderRoute: typeof KalenderEkonomiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisis/$slug': {
      id: '/analisis/$slug'
      path: '/$slug'
      fullPath: '/analisis/$slug'
      preLoaderRoute: typeof AnalisisSlugRouteImport
      parentRoute: typeof AnalisisRoute
    }
    '/edukasi/$slug': {
      id: '/edukasi/$slug'
      path: '/$slug'
      fullPath: '/edukasi/$slug'
      preLoaderRoute: typeof EdukasiSlugRouteImport
      parentRoute: typeof EdukasiRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
  }
}

interface AnalisisRouteChildren {
  AnalisisSlugRoute: typeof AnalisisSlugRoute
}

const AnalisisRouteChildren: AnalisisRouteChildren = {
  AnalisisSlugRoute: AnalisisSlugRoute,
}

const AnalisisRouteWithChildren = AnalisisRoute._addFileChildren(
  AnalisisRouteChildren,
)

interface EdukasiRouteChildren {
  EdukasiSlugRoute: typeof EdukasiSlugRoute
}

const EdukasiRouteChildren: EdukasiRouteChildren = {
  EdukasiSlugRoute: EdukasiSlugRoute,
}

const EdukasiRouteWithChildren =
  EdukasiRoute._addFileChildren(EdukasiRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisisRoute: AnalisisRouteWithChildren,
  EdukasiRoute: EdukasiRouteWithChildren,
  KalenderEkonomiRoute: KalenderEkonomiRoute,
  KontakRoute: KontakRoute,
  NewsRoute: NewsRouteWithChildren,
  ProfilRoute: ProfilRoute,
  StudioRoute: StudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
